name: 自动部署个人网站
on:
  push:
    branches: [ main ] # 只有推main分支才触发部署
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 安装Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 适配MkDocs，不用改
      - name: 安装依赖（MkDocs+Material主题）
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
      - name: 构建并部署
        run: |
          mkdocs gh-deploy --force